apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.15.3
          ports:
            - name: http-input
              containerPort: 8080
            - name: monitoring
              containerPort: 9600
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              cpu: 300m
              memory: 1Gi
            limits:
              cpu: "1"
              memory: 1Gi
          volumeMounts:
            - name: pipeline
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: pipeline
          configMap:
            name: logstash-pipeline
