apiVersion: v1
kind: Service
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
    - name: http-input
      port: 8080
      targetPort: 8080
    - name: monitoring
      port: 9600
      targetPort: 9600
