traefik:
  ingressRoute:
    dashboard:
      enabled: true
  ports:
    traefik:
      port: 8080
      expose:
        default: true
      exposedPort: 8080
      protocol: TCP
  service:
    type: LoadBalancer
    additionalPorts: 
      - name: traefik
        port: 8080
        targetPort: 8080
        protocol: TCP
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"