traefik:
  deployment:
    kind: Deployment
    replicas: 2
    healthchecksPort: 8000

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: traefik
            topologyKey: topology.kubernetes.io/zone

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

  ports:
    web:
      port: 8000
      expose:
        default: true
      exposedPort: 80
      protocol: TCP
    traefik:
      port: 9000
      expose:
        default: false
      protocol: TCP
    websecure:
      expose:
        default: false

  service:
    type: NodePort
    annotations: {}

  ping:
    enabled: true

  additionalArguments:
    - "--ping.entryPoint=web"
    - "--ping.terminatingStatusCode=503"

  ingressRoute:
    dashboard:
      enabled: true
      entryPoints: ["traefik"]
      matchRule: PathPrefix(`/dashboard`) || PathPrefix(`/api`)

  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true

    kubernetesIngress:
      enabled: false

  logs:
    general:
      level: INFO
    access:
      enabled: true
      format: json

  metrics:
    prometheus:
      service:
        enabled: true
      serviceMonitor:
        enabled: false

  rbac:
    enabled: true

  ingressClass:
    enabled: false

routing:
  app:
    serviceName: ktcloud-msa-user-api-gateway-release
    namespace: ktcloud-market-msa
    port: 80

  argocd:
    serviceName: argocd-server
    namespace: argocd
    port: 80
