apiVersion: v2
name: ktcloud-postgresql
description: PostgreSQL wrapper for multi-db setup
type: application
version: 1.0.0
appVersion: "17.4.0"

dependencies:
  - name: postgresql
    version: 16.7.0
    repository: oci://registry-1.docker.io/bitnamicharts