global:
  security:
    allowInsecureImages: true

  auth:
    postgresPassword: "admin1234"
    existingSecret: ""
    secretKeys:
      adminPasswordKey: ""
      userPasswordKey: ""
      replicationPasswordKey: ""
      metricsPasswordKey: ""

postgresql:
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.6.0-debian-12-r0
    pullPolicy: IfNotPresent
 
  primary:
    initdb:
      scripts: 
        init-db.sql: |
          CREATE DATABASE inventory_db;
          CREATE DATABASE product_db;
          CREATE DATABASE order_db;
          CREATE DATABASE auth_db;

          CREATE USER "inventory-service" WITH ENCRYPTED PASSWORD 'inventory-service';
          CREATE USER "product-service" WITH ENCRYPTED PASSWORD 'product-service';
          CREATE USER "order-service" WITH ENCRYPTED PASSWORD 'order-service';
          CREATE USER "auth-service" WITH ENCRYPTED PASSWORD 'auth-service';

          ALTER DATABASE inventory_db OWNER TO "inventory-service";
          \c inventory_db
          GRANT ALL ON SCHEMA public TO "inventory-service";

          ALTER DATABASE product_db OWNER TO "product-service";
          \c product_db
          GRANT ALL ON SCHEMA public TO "product-service";

          ALTER DATABASE order_db OWNER TO "order-service";
          \c order_db
          GRANT ALL ON SCHEMA public TO "order-service";

          ALTER DATABASE order_db OWNER TO "auth-service";
          \c auth_db
          GRANT ALL ON SCHEMA public TO "auth-service";