apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: Charts-app
spec:
  generators:
    - list:
        - path: Charts/Traefik
  template:
    metadata:
      name: '{{path}}'
    spec:
      project: default
      source:
        repoURL: "https://github.com/kanei0415/ktcloud-k8s-argocd-manifest.git"
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default