global:
  imagePullSecrets: []

  security:
    allowInsecureImages: true

redis:
  architecture: standalone

  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: 8.2.1-debian-12-r0
    pullSecrets: []

  auth:
    enabled: true
    password: "admin1234"

  sentinel:
    enabled: false
  metrics:
    enabled: false