global:
  imagePullSecrets: []

  security:
    allowInsecureImages: true

redis:
  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: latest
    pullSecrets: []
  
  auth:
    enabled: true
    password: "admin1234"
  
  sentinel:
    enabled: false
  metrics:
    enabled: false